version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432"  # host:container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  postgres_data:

networks:
  springboot-network:
